name:                imdb-stats
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/imdb-stats#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here
category:            Web
extra-source-files:
- README.md

ghc-options:
  - -threaded
  - -rtsopts

dependencies:
  - base >= 4.7 && < 5
  - containers
  - text
  - scalpel
  - extra
  - url
  - interpolate
  - aeson
  - bytestring
  - vector
  - attoparsec
  - async
  - deepseq

library:
  source-dirs: src

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - imdb-stats

tests:
  spec:
    main: Test.hs
    source-dirs:
      - test
    dependencies:
      - HUnit
      - imdb-stats

benchmarks:
  benchmark:
    main: Bench.hs
    source-dirs:
      - bench
    dependencies:
      - imdb-stats
      - criterion